dataset_repository: 
  component_type_key: DATASET_REPOSITORY
  variant_key: DEFAULT
  config:
    storage_connector_path: ./file_storage/

dataset_iterators: 
  component_type_key: DATASET_ITERATORS
  variant_key: DEFAULT
  requirements:
    - name: repository
      component_name: dataset_repository
  config:
    dataset_identifier: reuters
    splits: [train, test]

filtered_labels_iterator: 
  component_type_key: FILTERED_LABELS_ITERATOR
  variant_key: DEFAULT
  requirements:
    - name: iterators
      component_name: dataset_iterators
      subscriptions: [train, test]
  config:
    filtered_labels: [earn, acq, crude, trade, interest, money-fx, money-supply]
    applicable_splits: [train, test]

mapped_labels_iterator: 
  component_type_key: MAPPED_LABELS_ITERATOR
  variant_key: DEFAULT
  requirements:
    - name: iterators
      component_name: filtered_labels_iterator
      subscriptions: [train, test]
  config:
    mappings:
      - previous_labels: [crude, trade, interest, money-fx, money-supply]
        new_label: 1
      - previous_labels: [earn, acq]
        new_label: 0
    applicable_splits: [train, test]

splitted_dataset_iterators: 
  component_type_key: SPLITTED_DATASET_ITERATORS
  variant_key: RANDOM
  requirements:
    - name: iterators
      component_name: mapped_labels_iterator
      subscription: [train, test]
  config:
    split_configs:
      train:
        train: 0.7
        val: 0.3

data_collator: 
  component_type_key: DATA_COLLATOR
  variant_key: DEFAULT
  config:
    collator_type:
      injectable:
        id: id_mlp_standard_collator
    collator_params:
      target_publication_key: label_partition

data_loaders: 
  component_type_key: DATA_LOADER
  variant_key: DEFAULT
  requirements:
    - name: iterators
      component_name: splitted_dataset_iterators
      subscription: [train, val, test]
    - name: data_collator
      component_name: data_collator
  config:
    batch_size: 10
    weigthed_sampling_split_name: null
