global_config:
  storage_connector_path: &storage_path_anchor ./file_storage/
  seed: &seed_value 2
  split_seed: &split_seed 2
  target_class_key: &target_class_key_anchor target_class_key
  model_prediction_key: &model_prediction_key_anchor model_raw_prediction
  # postprocessing publication keys
  postprocessing_sigmoidal_key: &postprocessing_sigmoidal_key_anchor postprocessing_sigmoidal_key
  postprocessing_binarization_key: &postprocessing_binarization_key_anchor postprocessing_binarization_key

dataset_repository: 
  component_type_key: DATASET_REPOSITORY
  variant_key: DEFAULT
  config:
    storage_connector_path: *storage_path_anchor

dataset_iterators: 
  component_type_key: DATASET_ITERATORS
  variant_key: DEFAULT
  requirements:
    - name: repository
      component_name: dataset_repository
  config:
    dataset_identifier: reuters
    splits: [train, test]

filtered_labels_iterator: 
  component_type_key: FILTERED_LABELS_ITERATOR
  variant_key: DEFAULT
  requirements:
    - name: iterators
      component_name: dataset_iterators
      subscriptions: [train, test]
  config:
    filtered_labels: [earn, acq, crude, trade, interest, money-fx, money-supply]
    applicable_splits: [train, test]

mapped_labels_iterator: 
  component_type_key: MAPPED_LABELS_ITERATOR
  variant_key: DEFAULT
  requirements:
    - name: iterators
      component_name: filtered_labels_iterator
      subscriptions: [train, test]
  config:
    mappings:
      - previous_labels: [crude, trade, interest, money-fx, money-supply]
        new_label: 1
      - previous_labels: [earn, acq]
        new_label: 0
    applicable_splits: [train, test]

splitted_dataset_iterators: 
  component_type_key: SPLITTED_DATASET_ITERATORS
  variant_key: RANDOM
  requirements:
    - name: iterators
      component_name: mapped_labels_iterator
      subscription: [train, test]
  config:
    split_configs:
      train:
        train: 0.7
        val: 0.3
    seed: *split_seed

data_collator: 
  component_type_key: DATA_COLLATOR
  variant_key: DEFAULT
  config:
    collator_type:
      injectable:
        id: id_mlp_standard_collator
    collator_params:
      target_publication_key: *target_class_key_anchor

data_loaders: 
  component_type_key: DATA_LOADER
  variant_key: DEFAULT
  requirements:
    - name: iterators
      component_name: splitted_dataset_iterators
      subscription: [train, val, test]
    - name: data_collator
      component_name: data_collator
  config:
    batch_size: 10
    weigthed_sampling_split_name:
      sweep: absolute
      values: [train, null]

model_registry: 
  component_type_key: MODEL_REGISTRY
  variant_key: DEFAULT

model: 
  component_type_key: MODEL
  variant_key: DEFAULT
  requirements:
    - name: model_registry
      component_name: model_registry
      subscription: mlp
  config:
    model_definition:
      hidden_layer_config:
        - 50
      n_inputs: 100
      n_outputs: 1
    model_type: MLP
    seed: *seed_value
    prediction_publication_keys: 
      prediction_publication_key: *model_prediction_key_anchor

optimizer:
  component_type_key: OPTIMIZER
  variant_key: DEFAULT
  config:
    optimizer_key: ADADELTA
    params:
      lr:
        sweep: absolute
        values: [0.01, 0.001]

loss_function_registry: 
  component_type_key: LOSS_FUNCTION_REGISTRY
  variant_key: DEFAULT

metric_registry: 
  component_type_key: METRIC_REGISTRY
  variant_key: DEFAULT

prediction_postprocessing_registry: 
  component_type_key: PREDICTION_POSTPROCESSING_REGISTRY
  variant_key: DEFAULT

train_component: 
  component_type_key: TRAIN_COMPONENT
  variant_key: DEFAULT
  requirements:
    - name: loss_function_registry
      component_name: loss_function_registry
    - name: prediction_postprocessing_registry
      component_name: prediction_postprocessing_registry
  config:
    loss_fun_config:
      prediction_subscription_key: *model_prediction_key_anchor
      target_subscription_key: *target_class_key_anchor
      key: BCEWithLogitsLoss
      tag: binary_cross_entropy_with_logits_loss

trainer:
  component_type_key: TRAINER
  variant_key: DEFAULT
  requirements:
    - name: train_component
      component_name: train_component
    - name: model
      component_name: model
      subscription: null
    - name: data_loaders
      component_name: data_loaders
      subscription: train


eval_component: 
  component_type_key: EVAL_COMPONENT
  variant_key: DEFAULT
  requirements:
    - name: model
      component_name: model 
      subscription: null
    - name: data_loaders
      component_name: data_loaders 
      subscription: [train, val, test]
    - name: loss_function_registry
      component_name: loss_function_registry 
    - name: metric_registry
      component_name: metric_registry 
    - name: prediction_postprocessing_registry
      component_name: prediction_postprocessing_registry
  config:
    post_processors_config:
      - key: "SIGMOIDAL"
        prediction_subscription_key: *model_prediction_key_anchor
        prediction_publication_key: *postprocessing_sigmoidal_key_anchor
      - key: "BINARIZATION"
        prediction_subscription_key: *postprocessing_sigmoidal_key_anchor
        prediction_publication_key: *postprocessing_binarization_key_anchor
    train_split_name: train
    metrics_config:
      - key: AUPR
        params:
          average: macro
        prediction_subscription_key: *postprocessing_sigmoidal_key_anchor
        target_subscription_key: *target_class_key_anchor
        tag: AUPR_macro
      - key: AUROC
        params:
          average: macro
        prediction_subscription_key: *postprocessing_sigmoidal_key_anchor
        target_subscription_key: *target_class_key_anchor
        tag: AUROC_macro
      - key: F1_SCORE
        params:
          average: macro
        prediction_subscription_key: *postprocessing_binarization_key_anchor
        target_subscription_key: *target_class_key_anchor
        tag: F1_SCORE_macro
      - key: F1_SCORE
        params:
          average: binary
          pos_label: 1
        prediction_subscription_key: *postprocessing_binarization_key_anchor
        target_subscription_key: *target_class_key_anchor
        tag: F1_SCORE_binary
      - key: PRECISION
        params:
          average: macro
        prediction_subscription_key: *postprocessing_binarization_key_anchor
        target_subscription_key: *target_class_key_anchor
        tag: PRECISION_macro
      - key: PRECISION
        params:
          average: binary
          pos_label: 1
        prediction_subscription_key: *postprocessing_binarization_key_anchor
        target_subscription_key: *target_class_key_anchor
        tag: PRECISION_binary
      - key: RECALL
        params:
          average: macro
        prediction_subscription_key: *postprocessing_binarization_key_anchor
        target_subscription_key: *target_class_key_anchor
        tag: RECALL_macro
      - key: RECALL
        params:
          average: binary
          pos_label: 1
        prediction_subscription_key: *postprocessing_binarization_key_anchor
        target_subscription_key: *target_class_key_anchor
        tag: RECALL_binary
    loss_funs_config:
      - key: BCEWithLogitsLoss
        tag: binary_cross_entropy_with_logits_loss
        prediction_subscription_key: *model_prediction_key_anchor
        target_subscription_key: *target_class_key_anchor

evaluator:
  component_type_key: EVALUATOR
  variant_key: DEFAULT
  requirements:
    - name: eval_component
      component_name: eval_component
